import AsyncStorage from "@react-native-async-storage/async-storage";
import createContextHook from "@nkzw/create-context-hook";
import { useCallback, useEffect, useMemo, useState } from "react";
import { I18nManager } from "react-native";

type Language = "en" | "ar";

const STORAGE_KEY = "app_language";

export const [LanguageProvider, useLanguage] = createContextHook(() => {
  const [language, setLanguage] = useState<Language>("en");
  const [isRTL, setIsRTL] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isChanging, setIsChanging] = useState(false);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const stored = await AsyncStorage.getItem(STORAGE_KEY);
      if (stored === "ar" || stored === "en") {
        setLanguage(stored);
        setIsRTL(stored === "ar");
        I18nManager.forceRTL(stored === "ar");
      } else {
        I18nManager.forceRTL(false);
      }
    } catch (error) {
      console.error("Failed to load language:", error);
      I18nManager.forceRTL(false);
    } finally {
      setIsLoading(false);
    }
  };

  const changeLanguage = useCallback(async (newLanguage: Language) => {
    try {
      setIsChanging(true);
      await AsyncStorage.setItem(STORAGE_KEY, newLanguage);
      
      await new Promise(resolve => setTimeout(resolve, 300));
      
      setLanguage(newLanguage);
      setIsRTL(newLanguage === "ar");
      
      if (I18nManager.isRTL !== (newLanguage === "ar")) {
        I18nManager.forceRTL(newLanguage === "ar");
      }
    } catch (error) {
      console.error("Failed to save language:", error);
    } finally {
      setIsChanging(false);
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || key;
  }, [language]);

  return useMemo(
    () => ({
      language,
      isRTL,
      isLoading,
      isChanging,
      changeLanguage,
      t,
    }),
    [language, isRTL, isLoading, isChanging, changeLanguage, t]
  );
});

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Khedmah",
    home: "Home",
    explore: "Explore",
    inbox: "Inbox",
    orders: "Orders",
    profile: "Profile",
    search: "Search services...",
    categories: "Categories",
    popularGigs: "Popular Services",
    topRated: "Top Rated Freelancers",
    viewAll: "View All",
    startingAt: "Starting at",
    ordersInQueue: "orders in queue",
    reviews: "reviews",
    rating: "Rating",
    deliveryTime: "Delivery Time",
    days: "days",
    basic: "Basic",
    standard: "Standard",
    premium: "Premium",
    selectPackage: "Select Package",
    aboutThisGig: "About This Gig",
    aboutSeller: "About the Seller",
    memberSince: "Member since",
    languages: "Languages",
    skills: "Skills",
    portfolio: "Portfolio",
    graphicDesign: "Graphic Design",
    contentCreation: "Content Creation",
    translation: "Translation",
    socialMedia: "Social Media",
    digitalMarketing: "Digital Marketing",
    videoEditing: "Video Editing",
    webDevelopment: "Web Development",
    voiceOver: "Voice Over",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    online: "Online",
    offline: "Offline",
    messages: "Messages",
    active: "Active",
    completed: "Completed",
    cancelled: "Cancelled",
    inProgress: "In Progress",
    delivered: "Delivered",
    orderDetails: "Order Details",
    buyer: "Buyer",
    seller: "Seller",
    total: "Total",
    orderPlaced: "Order Placed",
    dueDate: "Due Date",
    status: "Status",
    viewOrder: "View Order",
    noMessages: "No messages yet",
    startConversation: "Start chatting with sellers",
    noOrders: "No orders yet",
    browseServices: "Browse services to get started",
    sellerDashboard: "Seller Dashboard",
    totalEarnings: "Total Earnings",
    thisMonth: "This Month",
    viewEarnings: "View Earnings",
    activeOrders: "Active Orders",
    responseTime: "Response Time",
    quickActions: "Quick Actions",
    myGigs: "My Gigs",
    createGig: "Create Gig",
    manageOrders: "Manage Orders",
    analytics: "Analytics",
    recentOrders: "Recent Orders",
    due: "Due",
    performance: "Performance",
    details: "Details",
    onTimeDelivery: "On-Time Delivery",
    pendingDelivery: "Pending Delivery",
    revisionRequested: "Revision Requested",
    create: "Create",
    paused: "Paused",
    editGig: "Edit Gig",
    pauseGig: "Pause Gig",
    activateGig: "Activate Gig",
    deleteGig: "Delete Gig",
    daysLeft: "days left",
    performanceMetrics: "Performance Metrics",
    responseRate: "Response Rate",
    avgRating: "Avg. Rating",
    conversionRate: "Conversion Rate",
    earningsTrend: "Earnings Trend",
    last6Months: "Last 6 Months",
    topPerformingGigs: "Top Performing Gigs",
    switchToSelling: "Switch to Selling",
    manageYourServices: "Manage your services and earnings",
    customOffer: "Custom Offer",
    offerTemplates: "Offer Templates",
    createCustomOffer: "Create Custom Offer",
    serviceTitle: "Service Title",
    description: "Description",
    price: "Price",
    deliveryDays: "Delivery Days",
    revisions: "Revisions",
    extras: "Extras",
    sendOffer: "Send Offer",
    offerSent: "Offer Sent",
    offerViewed: "Offer Viewed",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined",
    offerExpired: "Offer Expired",
    createNewOffer: "Create New Offer",
    addExtra: "Add an extra feature",
    unlimited: "Unlimited",
    paymentWarning: "All payments must be made through the platform to protect your rights",
    "view Details": "View Details",
    "in Progress": "In Progress",
    "pending Delivery": "Pending Delivery",
    "revision Requested": "Revision Requested",
    "manage Orders": "Manage Orders",
    "view Earnings": "View Earnings",
    "active Orders": "Active Orders",
    "quick Actions": "Quick Actions",
    "create Gig": "Create Gig",
    "edit Profile": "Edit Profile",
    "recent Orders": "Recent Orders",
    "on Time Delivery": "On-Time Delivery",
    "my Gigs": "My Gigs",
    "edit Gig": "Edit Gig",
    "pause Gig": "Pause Gig",
    "activate Gig": "Activate Gig",
    "delete Gig": "Delete Gig",
    "performance Metrics": "Performance Metrics",
    "earnings Trend": "Earnings Trend",
    "top Performing Gigs": "Top Performing Gigs",
    "active Order": "Active Order",
    "type Message": "Type a message...",
    "no Active Orders": "No active orders",
    "no Completed Orders": "No completed orders",
    "no Cancelled Orders": "No cancelled orders",
    revenue: "Revenue",
    searchConversations: "Search conversations...",
    noConversations: "No conversations yet",
    conversationsWillAppear: "Conversations will appear here",
    recentTransactions: "Recent Transactions",
    availableBalance: "Available Balance",
    withdrawFunds: "Withdraw Funds",
    pendingClearance: "Pending Clearance",
    platformFee: "Platform Fee",
    selectMethod: "Select Method",
    bankTransfer: "Bank Transfer",
    "3to5BusinessDays": "3-5 business days",
    debitCard: "Debit Card",
    instantTransfer: "Instant transfer",
    digitalWallet: "Digital Wallet",
    stcPayFawry: "STC Pay, Fawry",
    comingSoon: "Coming Soon",
    pending: "Pending",
    earnings: "Earnings",
    left: "left",
    edit: "Edit",
    settings: "Settings",
    dashboard: "Dashboard",
    adminDashboard: "Admin Dashboard",
    userManagement: "User Management",
    gigsManagement: "Gigs Management",
    disputesManagement: "Disputes Management",
    overview: "Overview",
    totalUsers: "Total Users",
    activeGigs: "Active Gigs",
    openDisputes: "Open Disputes",
    pendingSellers: "Pending Sellers",
    pendingGigs: "Pending Gigs",
    pendingPayouts: "Pending Payouts",
    needsAttention: "Needs Attention",
    reviewSellers: "Review Sellers",
    approveGigs: "Approve Gigs",
    resolveDisputes: "Resolve Disputes",
    approvePayouts: "Approve Payouts",
    searchUsers: "Search users...",
    approve: "Approve",
    reject: "Reject",
    suspend: "Suspend",
    verify: "Verify",
    more: "More",
    sar: "SAR",
  },
  ar: {
    appName: "خدمة",
    home: "الرئيسية",
    explore: "استكشف",
    inbox: "الرسائل",
    orders: "الطلبات",
    profile: "الملف الشخصي",
    search: "ابحث عن الخدمات...",
    categories: "التصنيفات",
    popularGigs: "الخدمات الشائعة",
    topRated: "أفضل المستقلين",
    viewAll: "عرض الكل",
    startingAt: "يبدأ من",
    ordersInQueue: "طلبات في الانتظار",
    reviews: "تقييمات",
    rating: "التقييم",
    deliveryTime: "وقت التسليم",
    days: "أيام",
    basic: "أساسي",
    standard: "قياسي",
    premium: "مميز",
    selectPackage: "اختر الباقة",
    aboutThisGig: "عن هذه الخدمة",
    aboutSeller: "عن البائع",
    memberSince: "عضو منذ",
    languages: "اللغات",
    skills: "المهارات",
    portfolio: "معرض الأعمال",
    graphicDesign: "التصميم الجرافيكي",
    contentCreation: "إنشاء المحتوى",
    translation: "الترجمة",
    socialMedia: "وسائل التواصل",
    digitalMarketing: "التسويق الرقمي",
    videoEditing: "تحرير الفيديو",
    webDevelopment: "تطوير المواقع",
    voiceOver: "التعليق الصوتي",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    online: "متصل",
    offline: "غير متصل",
    messages: "الرسائل",
    active: "نشط",
    completed: "مكتمل",
    cancelled: "ملغى",
    inProgress: "قيد التنفيذ",
    delivered: "تم التسليم",
    orderDetails: "تفاصيل الطلب",
    buyer: "المشتري",
    seller: "البائع",
    total: "الإجمالي",
    orderPlaced: "تاريخ الطلب",
    dueDate: "تاريخ التسليم",
    status: "الحالة",
    viewOrder: "عرض الطلب",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ المحادثة مع البائعين",
    noOrders: "لا توجد طلبات بعد",
    browseServices: "تصفح الخدمات للبدء",
    sellerDashboard: "لوحة البائع",
    totalEarnings: "إجمالي الأرباح",
    thisMonth: "هذا الشهر",
    viewEarnings: "عرض الأرباح",
    activeOrders: "الطلبات النشطة",
    responseTime: "وقت الاستجابة",
    quickActions: "إجراءات سريعة",
    myGigs: "خدماتي",
    createGig: "إنشاء خدمة",
    manageOrders: "إدارة الطلبات",
    analytics: "التحليلات",
    recentOrders: "الطلبات الأخيرة",
    due: "الاستحقاق",
    performance: "الأداء",
    details: "التفاصيل",
    onTimeDelivery: "التسليم في الوقت المحدد",
    pendingDelivery: "في انتظار التسليم",
    revisionRequested: "مطلوب تعديل",
    create: "إنشاء",
    paused: "متوقف",
    editGig: "تعديل الخدمة",
    pauseGig: "إيقاف الخدمة",
    activateGig: "تفعيل الخدمة",
    deleteGig: "حذف الخدمة",
    daysLeft: "أيام متبقية",
    performanceMetrics: "مقاييس الأداء",
    responseRate: "معدل الاستجابة",
    avgRating: "متوسط التقييم",
    conversionRate: "معدل التحويل",
    earningsTrend: "اتجاه الأرباح",
    last6Months: "آخر 6 أشهر",
    topPerformingGigs: "أفضل الخدمات أداءً",
    switchToSelling: "التحول إلى البيع",
    manageYourServices: "إدارة خدماتك وأرباحك",
    customOffer: "عرض مخصص",
    offerTemplates: "قوالب العروض",
    createCustomOffer: "إنشاء عرض مخصص",
    serviceTitle: "عنوان الخدمة",
    description: "الوصف",
    price: "السعر",
    deliveryDays: "أيام التسليم",
    revisions: "التعديلات",
    extras: "الإضافات",
    sendOffer: "إرسال العرض",
    offerSent: "تم الإرسال",
    offerViewed: "تمت المشاهدة",
    offerAccepted: "مقبول",
    offerDeclined: "مرفوض",
    offerExpired: "منتهي",
    createNewOffer: "إنشاء عرض جديد",
    addExtra: "أضف ميزة إضافية",
    unlimited: "غير محدود",
    paymentWarning: "جميع المدفوعات يجب أن تتم من خلال المنصة لحماية حقوقك",
    "view Details": "عرض التفاصيل",
    "in Progress": "قيد التنفيذ",
    "pending Delivery": "في انتظار التسليم",
    "revision Requested": "مطلوب تعديل",
    "manage Orders": "إدارة الطلبات",
    "view Earnings": "عرض الأرباح",
    "active Orders": "الطلبات النشطة",
    "quick Actions": "إجراءات سريعة",
    "create Gig": "إنشاء خدمة",
    "edit Profile": "تعديل الملف",
    "recent Orders": "الطلبات الأخيرة",
    "on Time Delivery": "التسليم في الوقت المحدد",
    "my Gigs": "خدماتي",
    "edit Gig": "تعديل الخدمة",
    "pause Gig": "إيقاف الخدمة",
    "activate Gig": "تفعيل الخدمة",
    "delete Gig": "حذف الخدمة",
    "performance Metrics": "مقاييس الأداء",
    "earnings Trend": "اتجاه الأرباح",
    "top Performing Gigs": "أفضل الخدمات أداءً",
    "active Order": "طلب نشط",
    "type Message": "اكتب رسالة...",
    "no Active Orders": "لا توجد طلبات نشطة",
    "no Completed Orders": "لا توجد طلبات مكتملة",
    "no Cancelled Orders": "لا توجد طلبات ملغاة",
    revenue: "الإيرادات",
    searchConversations: "البحث في المحادثات...",
    noConversations: "لا توجد محادثات بعد",
    conversationsWillAppear: "ستظهر المحادثات هنا",
    recentTransactions: "المعاملات الأخيرة",
    availableBalance: "الرصيد المتاح",
    withdrawFunds: "سحب الأموال",
    pendingClearance: "في انتظار المقاصة",
    platformFee: "رسوم المنصة",
    selectMethod: "اختر الطريقة",
    bankTransfer: "تحويل بنكي",
    "3to5BusinessDays": "3-5 أيام عمل",
    debitCard: "بطاقة الخصم",
    instantTransfer: "تحويل فوري",
    digitalWallet: "المحفظة الرقمية",
    stcPayFawry: "STC Pay، فوري",
    comingSoon: "قريباً",
    pending: "قيد الانتظار",
    earnings: "الأرباح",
    left: "متبقي",
    edit: "تعديل",
    settings: "الإعدادات",
    dashboard: "لوحة التحكم",
    adminDashboard: "لوحة التحكم",
    userManagement: "إدارة المستخدمين",
    gigsManagement: "إدارة الخدمات",
    disputesManagement: "إدارة النزاعات",
    overview: "نظرة عامة",
    totalUsers: "إجمالي المستخدمين",
    activeGigs: "الخدمات النشطة",
    openDisputes: "نزاعات مفتوحة",
    pendingSellers: "بائعون بانتظار الموافقة",
    pendingGigs: "خدمات بانتظار الموافقة",
    pendingPayouts: "طلبات سحب معلقة",
    needsAttention: "يحتاج إلى انتباه",
    reviewSellers: "مراجعة البائعين",
    approveGigs: "الموافقة على الخدمات",
    resolveDisputes: "حل النزاعات",
    approvePayouts: "موافقة السحوبات",
    searchUsers: "بحث عن المستخدمين...",
    approve: "موافقة",
    reject: "رفض",
    suspend: "إيقاف",
    verify: "توثيق",
    more: "المزيد",
    sar: "ريال",
  },
};
